---
apiVersion: sealer.aliyun.com/v1alpha1
kind: Plugin
metadata:
  name: SHELL
spec:
  action: PreInstall
  data: |
    cd /var/lib/sealer/data/my-cluster/rootfs/yrcloudfile && chmod 0755 all.sh && sh -x all.sh 192.168.13.28 8080
---
apiVersion: sealer.aliyun.com/v1alpha1
kind: Config
metadata:
  name: yrcloudfile.yml
spec:
  path: etc/yrcloudfile.yml
  data: |
    hosts:
    - hostname: node28.yr
      mds_disks: [/dev/sdb,/dev/sdc]
      mgmt_network: {device: ens224, ipaddr: 192.168.13.28}
      oss_disks: [/dev/sdd, /dev/sde]
      password: Passw0rd
      roles: [mds, oss, mgr] 
    - hostname: node29.yr
      mds_disks: [/dev/sdb,/dev/sdc]
      mgmt_network: {device: ens224, ipaddr: 192.168.13.29}
      oss_disks: [/dev/sdd, /dev/sde]
      password: Passw0rd
      roles: [mds, oss, mgr]
    - hostname: node35.yr
      mds_disks: [/dev/sdb,/dev/sdc]
      mgmt_network: {device: ens224, ipaddr: 192.168.13.35}
      oss_disks: [/dev/sdd, /dev/sde]
      password: Passw0rd
      roles: [mds, oss, mgr]
    mgmt_cidr: 192.168.0.0/16
    mode: install
    owner: sealer
    http_port: 8080
    etcd_port: 2479
    etcd_peer_port: 2480
    mount_path: /mnt/pfs
    storage_cidr: 192.168.0.0/16
    version: 6.6.2
---
apiVersion: zlink.aliyun.com/v1alpha1
kind: Cluster
metadata:
  creationTimestamp: null
  name: my-cluster
spec:
  certSANS:
  - aliyun-inc.com
  - 10.0.0.2
  image: registry.cn-qingdao.aliyuncs.com/yrcloudfile/yrcloudfile:latest
  masters:
    count: "1"
    cpu: "4"
    dataDisks:
    - "100"
    ipList:
    - 192.168.13.28
    memory: "4"
    systemDisk: "100"
  network:
    podCIDR: 100.64.0.0/10
    svcCIDR: 10.96.0.0/22
  nodes:
    count: "0"
    cpu: "4"
    dataDisks:
    - "100"
    ipList:
    - 192.168.13.29
    - 192.168.13.35
    memory: "4"
    systemDisk: "100"
  provider: BAREMETAL
  ssh:
    passwd: Passw0rd
    pk: /root/.ssh/id_rsa
    user: root
status: {}
