apiVersion: zlink.aliyun.com/v1alpha1
kind: Cluster
metadata:
  creationTimestamp: null
  name: my-cluster
spec:
  certSANS:
    - aliyun-inc.com
    - 10.0.0.2
  image: registry.cn-qingdao.aliyuncs.com/sealer-apps/openebs-jiva:2.11.0
  masters:
    count: "1"
    cpu: "4"
    dataDisks:
      - "100"
    memory: "4"
    systemDisk: "100"
  network:
    podCIDR: 100.64.0.0/10
    svcCIDR: 10.96.0.0/22
  nodes:
    count: "3"
    cpu: "4"
    dataDisks:
      - "100"
    memory: "4"
    systemDisk: "100"
  provider: CONTAINER
  ssh:
    passwd: Seadent123
    pk: xxx
    pkPasswd: xxx
    user: root
---
apiVersion: sealer.aliyun.com/v1alpha1
kind: Plugin
metadata:
  name: SHELL
spec:
  action: PostInstall
  on: role=node
  data: |
    if type yum >/dev/null 2>&1;then
    yum -y install iscsi-initiator-utils
    systemctl enable iscsid
    systemctl start iscsid
    elif type apt-get >/dev/null 2>&1;then
    apt-get update
    apt-get -y install open-iscsi
    systemctl enable iscsid
    systemctl start iscsid
    fi
---
